### ISSUE TITLE
Larger caves

### ISSUE THREAD

**Issue by MrBlasyMSK** [Muqsit/VanillaGenerator#31] opened 2022-03-19 15:35 UTC
The caves are extremely small
![Captura de pantalla (485)](https://user-images.githubusercontent.com/85447029/159127652-a8cc5acc-9d74-44e7-b653-65de11465f69.png)

**Comment by Muqsit** [comment] 2022-03-19 16:00
Duplicate of #30

**Closed by Muqsit** 2022-03-19 16:00 UTC
